name: Build & Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: |
          npm install turbo -g
          npm i
          turbo run build --filter=web
          cp -r apps/web/.next/standalone/apps/web/. apps/web/.next/standalone
          cp apps/web/staticwebapp.config.json apps/web/.next
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_WAVE_0A47E7A0F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          skip_app_build: true
          app_location: "apps/web"
          api_location: ""
          output_location: ""
